# RevERP Configuration File

# Physics constants
physics:
  density: 1.3  # kg/m^3
  speed_of_sound: 343.0  # m/s
  reference_power: 1.0e-12  # W

# Analysis settings
analysis:
  analysis_type: "spectral"  # Can be "modal", "spectral", or "harmonic"
  spherical_harmonics: 200  # Number of spherical harmonics to use

  # Modal analysis settings
  modal_frequency_resolution: 5  # Hz - Resolution for frequency sweep
  modal_frequency_range: 5  # Analyze up to n times max natural frequency

  minimum_frequency: 0                                                          # Hz (Not yet implemented -> waiting for pyAnsys to update operator)
  maximum_frequency: 1000                                                       # Hz (Not yet implemented -> waiting for pyAnsys to update operator)

  clear_before_run: true
  dump_results: true
  dump_dir: 'results'

  sphere_area_compensation: true                                                #MUST BE IMPLEMENTED TO HANDLE POOR ASPECT RATIO

# Spherical Density Equalizing Map settings
SDEM_projection:
  SDEM: true
  SDEM_itt: 30
  SDEM_dt: 1
  SDEM_eps: 1.0e-5


  shrink_wrap_stl: #C:\Users\105849\Desktop\scala_wrap.stl
  shrink_wrap_map_filter_radius: 1.0e-3 # m

# Visualization settings
visualization:
    # Common settings
    save_plots: false
    plot_dir: 'plots'

    # Harmonic analysis plots
    result_summary_plot: true  # Overall summary plot
    erp_plot: false  # ERP comparison plot

    # Modal analysis plots
    modal_summary_plot: false  # Comprehensive modal analysis summary
    mode_comparison_plot: true  # Natural frequencies and radiation efficiencies
    frequency_sweep_plot: true  # Detailed frequency sweep analysis

    # SDEM plots
    SDEM_plot: true

    # Plot appearance
    figure_size: [12, 8]  # Default figure size [width, height]
    dpi: 100  # Plot resolution
    colormap: 'viridis'  # Default colormap for plots

# Logging settings
logging:
  level: "INFO"  # Can be DEBUG, INFO, WARNING, ERROR
  file: "logs/reverp.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"